"""update_user_id

Revision ID: 91f11f299cd5
Revises: 7d98efa025ab
Create Date: 2025-05-21 21:18:00.753540

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "91f11f299cd5"
down_revision = "7d98efa025ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_urls_user_id", table_name="urls")
    op.create_index(op.f("ix_urls_user_id"), "urls", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urls_user_id"), table_name="urls")
    op.create_index("ix_urls_user_id", "urls", ["user_id"], unique=False)
    # ### end Alembic commands ###
