"""add constraints

Revision ID: c81d6d04f072
Revises: 412c96121c9d
Create Date: 2026-01-23 13:08:51.777547

"""

# revision identifiers, used by Alembic.
revision = "c81d6d04f072"
down_revision = "412c96121c9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
