"""new_fields

Revision ID: 7d98efa025ab
Revises: 935a0dccf0b0
Create Date: 2025-05-04 23:39:39.095345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d98efa025ab'
down_revision = '935a0dccf0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('urls', sa.Column('name', sa.String(), nullable=True))
    op.add_column('urls', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('urls', sa.Column('last_used', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_urls_user_id'), 'urls', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_user_id'), table_name='urls')
    op.drop_column('urls', 'last_used')
    op.drop_column('urls', 'created_at')
    op.drop_column('urls', 'name')
    op.drop_column('urls', 'user_id')
    # ### end Alembic commands ###
