"""init3

Revision ID: 730111f6ffcc
Revises: f32fa217f816
Create Date: 2025-04-08 01:52:54.324174

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "730111f6ffcc"
down_revision = "f32fa217f816"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_urls_target_url", table_name="urls")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_urls_target_url", "urls", ["target_url"], unique=False)
    # ### end Alembic commands ###
