"""init4

Revision ID: 935a0dccf0b0
Revises: 730111f6ffcc
Create Date: 2025-04-08 02:00:43.338188

"""

# revision identifiers, used by Alembic.
revision = "935a0dccf0b0"
down_revision = "730111f6ffcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
