"""update_id

Revision ID: 270922bb3f80
Revises: f2f3a6c20412
Create Date: 2025-05-23 23:18:40.672086

"""

# revision identifiers, used by Alembic.
revision = "270922bb3f80"
down_revision = "f2f3a6c20412"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
