"""update_user_id

Revision ID: f2f3a6c20412
Revises: 91f11f299cd5
Create Date: 2025-05-23 22:43:58.811750

"""

# revision identifiers, used by Alembic.
revision = "f2f3a6c20412"
down_revision = "91f11f299cd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
