"""add click_inbox table

Revision ID: 412c96121c9d
Revises: 270922bb3f80
Create Date: 2025-12-18 16:18:03.101513

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "412c96121c9d"
down_revision = "270922bb3f80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "click_inbox",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("url_key", sa.String(length=5), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_click_inbox")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("click_inbox")
    # ### end Alembic commands ###
